[WIP] Docs review of schema description fields
stripe/stripe-apps pull request #716
Opened 2022-08-22 21:02 UTC by zsc-stripe

## Summary

This PR provides editorial review of schema description fields by the docs team at Stripe.

## Motivation

A better user experience through clarity and precision.

2022-08-23 21:53 UTC, zsc-stripe commented
Commit 6215a521fc5c8f22beae4e5c5f90d2c7d0fd92aa uses triple carats `^^^` to enable suggestions/commits from another editor.

2022-08-29 20:20 UTC, andresmitchell requested changes
Editor comments.

2022-08-29 20:20 UTC, andresmitchell commented on schema/stripe-app.schema.json
> +                "description": "^^^The events that will be sent to the webhook.",
```suggestion
                "description": "^^^The events that we send to the webhook.",
```

2022-08-29 20:20 UTC, andresmitchell commented on schema/stripe-app.schema.json
> +      "description": "^^^Specify a recommended action users should take after installing your app. Read more about post-install actions: https://stripe.com/docs/stripe-apps/post-install-actions",
```suggestion
      "description": "^^^Specify a recommended action for users to take after installing your app. Read more about post-install actions: https://stripe.com/docs/stripe-apps/post-install-actions",
```

2022-08-29 20:20 UTC, andresmitchell commented on schema/stripe-app.schema.json
> +      "description": "^^^Configuration options related to the display of the app in the Dashboard.",
```suggestion
      "description": "^^^Configuration options for how to display the app in the Dashboard.",
```

2022-08-29 20:20 UTC, andresmitchell commented on schema/stripe-app.schema.json
> +          "description": "^^^Configure where the app will appear within the Dashboard.",
```suggestion
          "description": "^^^Configure where the app appears in the Dashboard.",
```

2022-08-29 20:20 UTC, andresmitchell commented on schema/stripe-app.schema.json
> +                "description": "^^^An identifier that indicates where a UI extension will appear within the Dashboard. Read more about viewports: https://stripe.com/docs/stripe-apps/reference/viewpor
```suggestion
                "description": "^^^An identifier that indicates where a UI extension appears in the Dashboard. Read more about viewports: https://stripe.com/docs/stripe-apps/reference/viewports",
```

2022-08-29 20:20 UTC, andresmitchell commented on schema/stripe-app.schema.json
> +                "markdownDescription": "^^^An identifier that indicates where a UI extension will appear within the Dashboard. [Read more about viewports](https://stripe.com/docs/stripe-apps/referenc
```suggestion
                "markdownDescription": "^^^An identifier that indicates where a UI extension appears in the Dashboard. [Read more about viewports](https://stripe.com/docs/stripe-apps/reference/viewports).",
```

2022-08-29 20:20 UTC, andresmitchell commented on schema/stripe-app.schema.json
> +              "description": "^^^An message to show users when the app is installed that explains why the app needs to communicate with external URLs.",
```suggestion
              "description": "^^^A message to show users when the app is installed that explains why the app needs to communicate with external URLs.",
```

2022-08-29 20:20 UTC, andresmitchell commented on schema/stripe-app.schema.json
> +      "description": "^^^The recommended action users should take after installing your app. Read about post-install actions: https://stripe.com/docs/stripe-apps/post-install-actions",
```suggestion
      "description": "^^^The recommended action for users to take after installing your app. Read about post-install actions: https://stripe.com/docs/stripe-apps/post-install-actions",
```

2022-08-29 20:20 UTC, andresmitchell commented on schema/stripe-app.schema.json
> +      "markdownDescription": "^^^The recommended action users should take after installing your app. [Read about post-install actions](https://stripe.com/docs/stripe-apps/post-install-actions)."
```suggestion
      "markdownDescription": "^^^The recommended action for users to take after installing your app. [Read about post-install actions](https://stripe.com/docs/stripe-apps/post-install-actions)."
```

2022-08-29 21:39 UTC, zsc-stripe commented
@ericfrank-stripe 👋 PTAL

2022-08-29 21:41 UTC, ericfrank-stripe approved these changes

2022-08-30 19:22 UTC, merged